accounts/urls.py
from django.urls import path, include
from django.contrib.auth import urls as auth_urls

from . import views

app_name = "accounts"
urlpatterns = [
    path("", include(auth_urls)),
    path("register/", views.register, name="register"),
]

blogs/urls.py
from django.urls import path

from . import views

app_name = "blogs"
urlpatterns = [
    path("blogs/", views.blogs, name="blogs"),
    path("blogs/<int:blog_id>/", views.blog, name="blog"),
    path("posts/<int:post_id>/", views.post, name="post"),
    path("", views.index, name="index"),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User


class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.title

class BlogPost(models.Model):
    title = models.CharField(max_length=500)
    body = models.TextField()
    blog = models.ForeignKey(Blog,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title[:50]

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth import login

def register(request):
    if request.method != "POST":
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect("blogs:index")

    context = {"form": form}
    return render(request, "registration/register.html", context)

blogs/views.py
from django.shortcuts import render

from .models import Blog, BlogPost

def index(request):
    return render(request, "blogs/index.html")

def blogs(request):
    all_blogs = Blog.objects.all()
    context = {"blogs": all_blogs}
    return render(request, "blogs/blogs.html", context)

def blog(request, blog_id):
    blog = Blog.objects.get(id=blog_id)
    posts = blog.blogpost_set.all()
    
    context = {
        "blog": blog,
        "posts": posts,
    }
    return render(request, "blogs/blog.html", context)


def post(request, post_id):
    post = BlogPost.objects.get(id=post_id)
    blog = post.blog

    context = {
        "post": post,
        "blog": blog,
    }
    return render(request,  "blogs/post.html", context)

blogs/templates/blogs/base.html
{% load static %}

<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link href="{% static 'chota.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'custom.css' %}" rel="stylesheet" type="text/css">
    
    <title>BlogMaker Lite</title>
  </head>

  <body>
    <nav class="nav">
      <div class="nav-left">
        <a class="active" href="{% url 'blogs:index' %}">BlogMaker Lite</a>
        <a href="{% url 'blogs:blogs' %}">All blogs</a>
      </div>

      <div class="nav-right">
        {% if user.is_authenticated %}
          <span class="is-vertical-align">
            Hello, {{ user.username }}.</span>

          <form action="{% url 'accounts:logout' %}" method="post"
              class="is-vertical-align">
            {% csrf_token %}
            <button class="button outline">Log out</button>
          </form>

        {% else %}
          <a href="{% url 'accounts:login' %}">Log in</a>
          <a href="{% url 'accounts:register' %}">Register</a>
        {% endif %}
      </div>
    </nav>

    <div class="container">
      {% block content %}{% endblock content %}
    </div>
    
  </body>
</html>

blogs/templates/blogs/blog.html
{% extends "base.html" %}

{% block content %}

  <h2>{{ blog.title }}</h2>
  <p class="text-right blog-owner">{{ blog.owner.username }}</p>

  {% for post in posts %}

  <div class="card">
    <header>
      <h3>
        <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
      </h3>
    </header>
    <p>{{ post.date_added|date:"DATE_FORMAT"}}
    <p>{{ post.body|truncatewords:10 }}</p>
  </div>
    
  {% empty %}
    <h3>No posts have been written yet.</h3>
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/blogs.html
{% extends "blogs/base.html" %}

{% block content %}

  <h2>Blogs</h2>

  {% for blog in blogs %}

    <div class="card">
      <header>
        <h3>
          <a href="{% url 'blogs:blog' blog.id %}">{{ blog.title }}</a>
        </h3>
      </header>
      <p>{{ blog.description }}</p>
      <p class="text-right">{{ blog.owner.username }}</p>
    </div>
    
  {% empty %}
    <h3>No blogs have been added yet.</h3>
  {% endfor %}

{% endblock content %}

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block content %}

  <div class="hero">
    <p><span class="title">BlogMaker Lite</span> lets you share your thoughts with the world.</p>
    <p>Make a blog today, and let us know what you're thinking!</p>
  </div>

  <a class="button primary" href="{% url 'blogs:blogs' %}">
    See all blogs</a>
    
{% endblock content %}

blogs/templates/blogs/post.html
{% extends "base.html" %}

{% block content %}

  <h2>{{ post.title }}</h2>

  <div class="text-right">
    <span>{{ post.date_added|date:"DATE_FORMAT"}}</span> |
    <span>
      <a href="{% url 'blog' blog.id %}">{{ blog.title }}</a>
    </span>
    </div>

{% endblock content %}


  